//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720LONG_61133899.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class SinhVien
    {
        [Required(ErrorMessage =("Không được để trống"))]
        public string MaSV { get; set; }
        [Required(ErrorMessage = ("Không được để trống"))]
        public string HoSV { get; set; }
        [Required(ErrorMessage = ("Không được để trống"))]
        public string TenSV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = ("Không được để trống"))]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = true)]
        public string AnhSV { get; set; }
        public string DiaChi { get; set; }
        public string MaLop { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
